### ISSUE TITLE
Response to Feldon et al. "Null Effects of boot camps and short-format training" 

### ISSUE THREAD

**Issue by karenword** [carpentries/conversations#13]
We've identified a need for a thorough response to this paper: https://dx.doi.org/10.1073/pnas.1705783114  "Null effects of boot camps and short-format training for PhD students in life sciences"

An early draft response and comments is happening in this google doc:
https://docs.google.com/document/d/1w_YBZESCHjijpOmaNXB5PAJQ-RXZlZOYlQCJn-r2T3o/edit#

Maybe this will be a blog post soon? Please weigh in with your thoughts and comments!

**Comment by kariljordan** [comment]
A [response](https://datacarpentry.org/blog/2017/12/reponse-to-null-effects) to the Null Effects paper was published on Data Carpentry's blog on December 11, 2017.

On February 2, 2018, we held a webinar with Dr. Rochelle Tractenburg to discuss the null effects paper. You can find that [blog Post Summary](https://datacarpentry.org/blog/2018/03/tractenberg-summary) as well.

Closing this issue. Feel free to reopen if there is more to share.
