### ISSUE TITLE
What should be required for a "*** Carpentry" workshop to use the brand?

### ISSUE THREAD

**Issue by jduckles** [carpentries/conversations#16]
Software Carpentry's Steering Committee for the past several years has said that a Software Carpentry workshop must teach:
* Shell
* Programming (R, Python or Matlab)
* Git

Data Carpentry has had the guidance that Data Carpentry lessons
>follow a narrative structure, working with one dataset through the whole data lifecycle from data and project organization to data analysis and visualization.

Data Carpentry lessons are not allowed to be remixed because of this narrative structure. 

Much of what is common about Software/Data/Library Carpentry to me is:
* using trained instructors
* our culture of instruction (fun, engaging, supportive)
* live coding
* an enforced code of conduct
* balancing lecture/hands-on time
* two-day constraint

Some discussion questions:
* How do we codify this into a community opinion of what it takes to be a workshop that can be called a Carpentry?
* How should this reflect into lesson selection and acceptable use of branding as we grow?
* How do we stay flexible to workshop/teaching/lesson innovation by our instructors?

**Comment by ChristinaLK** [comment]
I would add that there's a commonality of teaching "best practices" -- not just how to use a particular tool, but why/when you would use that tool and how that tool contributes to an overall "ethos."  For research, that ethos often includes reproducibility, in other contexts, it might be efficiency (or discovery, or collaboration, or...)

**Comment by ctb** [comment]
@jduckles @ChristinaLK love this list!

I would add "insistent on using open materials that are available after the workshop".

**Comment by sheraaronhurt** [comment]
For a workshop to be branded as a Carpentries workshop we require the following:

 Carpentries workshop must meet the following requirements:

  - Teach a lesson program's core curriculum
  - Have at least one certified instructor
  - Must use The Carpentries curriculum
  - Use The Carpentries surveys to get evaluations
  - Abide by The Carpentries Code of Conduct.

The Lesson Programs requirements are as follows: 
- SWC as mentioned above.... must teach Shell, Git and a language. 
- DC must teach 3 sections and one must be Data organisation
- LC any 3 lessons from the curriculum

All of this can be found on the [workshops section of our website](https://carpentries.org/workshops/#workshop-core)

Would this be enough to close this issue?

**Comment by sheraaronhurt** [comment]
In absence of a response I am going to close this issue. If you have additional information, please re-open!
