### ISSUE TITLE
Recommendations for resources for after workshops

### ISSUE THREAD

**Issue by tracykteal** [carpentries/conversations#18]
We know we can't teach everything in two days, so it's great to give learners pointers to things they can use for continued learning or as resources after the workshop. 

We have links in a lot of our lessons right now, but some could use updating, and there might be general ones that aren't tied to a particular lesson. What are your favorite resources that you would recommend to learners after a workshop? Or pages that already collect lists of resources?

We can take information collected here and make a general 'resources sheet' and add to particular lessons as relevant.

**Comment by tracykteal** [comment]
For plotting and visualization:
- [Python graph galler](https://python-graph-gallery.com/)
- [R Graphics Cookbook](http://www.cookbook-r.com/Graphs/)

Just ran across this one, which looks interesting
- [Field Guide to the R Ecosystem](http://fg2re.sellorm.com/)

**Comment by jules32** [comment]
Hi @tracykteal, 

I think for R, Wickham & Grolemond's [R for Data Science](http://r4ds.had.co.nz/) is the best next step after Carpentries workshops. 

I also put together two lists: [Resources for learning R and Data Science](http://ohi-science.org/news/Resources-for-R-and-Data-Science) and [The importance of open data science tools in science](http://ohi-science.org/news/importance-of-open-data-science-tools).

Hope this is helpful!

**Comment by dgkeyes** [comment]
Here are a few that I'd add: [R Eco data science tutorials](https://github.com/eco-data-science), [Tidyverse style guide](http://style.tidyverse.org/), and [Kieran Healy's book Data Visualization for Social Science](http://vissoc.co/). A [recent post by Steph de Silva](http://rex-analytics.com/things-live-r-r-excel-users/) on explaining R to Excel users is also possibly helpful.

**Comment by tracykteal** [comment]
Jake VanderPlas' 'Python Data Science Handbook'

https://jakevdp.github.io/PythonDataScienceHandbook/

**Comment by willingc** [comment]
Brandon Rhodes's PyCon 2015 tutorial on pandas https://github.com/brandon-rhodes/pycon-pandas-tutorial

**Comment by aflaxman** [comment]
Here is a notebook that I used to teach intro pandas once, not sure how well it stands alone:

	https://github.com/jakevdp/2014_fall_ASTR599/blob/master/notebooks/15_PandasIntro.ipynb

**Comment by stijnvanhoey** [comment]
For the Doctoral schools at Ghent university, the Pandas oriented course provides notebooks on individual pandas concepts/fundamentals as well as case studies (one of the case studies is based on the biodiversity case of the carpentries) to apply these concepts: https://github.com/jorisvandenbossche/DS-python-data-analysis/tree/master/notebooks

It also corresponds with the material provided for the pandas tutorial at EuroScipy 2015 and 2016 by @jorisvandenbossche.

**Comment by laufers** [comment]
We send out a list of items to the learner as well as put them in the etherpad. They are in our helps repo https://github.com/oulib-swc/ouswc_workshop_helps and are called Resources for Continue Learning. ouswc_workshop_helps/Resources_for_Continue_Learning.md

**Comment by sheraaronhurt** [comment]
The CT is working on resources for each group in our community. The WAT will work on this more in-depth in 2022 and will share the resources.

**Comment by dgkeyes** [comment]
If it's helpful, I made a searchable, filterable collection of resources [here](https://rfortherestofus.com/resources/).

**Comment by sheraaronhurt** [comment]
Thanks everyone for this feedback. The Instructor Development Committee will be taking these recommendations and creating a resource sheet type of document. I'm closing this issue now :)
