### ISSUE TITLE
Is the README intending to link ErinBecker/conversations?

### ISSUE THREAD

**Issue by wking** [carpentries/conversations#2]
Current link is [here](https://github.com/carpentries/conversations/blame/8547ba3e1bd8b64e621dffbed67dec9c3fa4d03b/README.md#L6).

It looks like ErinBecker/conversations#1 was a precursor to #1.  Perhaps the README should be updated to link to #1 and ErinBecker/conversations#1 should be closed with “seeded carpentries/conversations#1”?

**Comment by ErinBecker** [comment]
@wking Thank you for catching the old link. I was testing out the wording and structure of the repository in my own GitHub account to make sure it was set up in a way that makes sense (I'm pretty new to GitHub). I've deleted the old repo on my account to avoid further confusion and corrected the link.
