### ISSUE TITLE
Merging of Zenodo communities

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/conversations#20]
Currently we have both a Data Carpentry https://zenodo.org/communities/datacarpentry and a SWC (https://zenodo.org/communities/swcarpentry) community on Zenodo. Should we attempt to merge them? Should we start also publishing new releases under a new Carpentries community?

**Comment by ErinBecker** [comment]
I think I published the DC Ecology and DC Genomics lessons under the SWC organization because I didn't know the DC one existed. I would be in favor of merging these communities on Zenodo and renaming to Carpentries.

**Comment by fmichonneau** [comment]
After spending a few minutes looking into this more, we can't easily merge organizations. We can however remove a release from an organization. So we could go in each lesson and add the new "Carpentries" organization (https://zenodo.org/communities/carpentries) to the records, and remove SWC, DC or LC. Because we can have multiple communities associated with a release, we may also want to include both "The Carpentries" and either SWC, DC or LC for each release.

**Comment by tracykteal** [comment]
I think having both 'Carpentries' and SWC, DC or LC as communities on the releases is a good idea.

**Comment by serahrono** [comment]
@fmichonneau any pending tasks / updates for this issue?

**Comment by fmichonneau** [comment]
I think the current approach of having 4 communities (carpentries, SWC, DC, LC) and using Carpentries + the relevant lesson program works well.
