### ISSUE TITLE
CarpentryCon2020 T-shirt Design Contest 

### ISSUE THREAD

**Issue by sstevens2** [carpentries/conversations#22]
Hi Carpentries Community Members!  

Bring your artistic skills to CarpentryCon2020 (even if you can't attend)!  Reply to this issue with your t-shirt design submission.  Remember the theme is "Growing Inclusive, Computational Communities and Leaders".  

Not submitting a design, upvote the ones you like best!  

Due Date for Submission: March 20, 2020 
Due Date for Voting: March 20, 2020

**Comment by ErinBecker** [comment]
I know this isn't a full t-shirt design, but throwing this in here in case anyone wants to incorporate it into a full design (e.g. add text). 
[Warhol_four_panel.pdf](https://github.com/carpentries/conversations/files/3893248/Warhol_four_panel.pdf)
![Warhol_four_panel](https://user-images.githubusercontent.com/19176319/69658273-b9ce4880-1030-11ea-8cb7-ce6e07581b85.png)

GH won't let me attach an SVG, but it's available here: https://github.com/ErinBecker/carpentries_art/blob/master/Warhol_four_panel.svg

**Comment by ErinBecker** [comment]
I've also got The Carpentries logo in various skin tones and rainbow colors: 

![skin_tones](https://user-images.githubusercontent.com/19176319/69658543-3fea8f00-1031-11ea-87e8-7b6d15e0b31c.png)

![rainbow-people](https://user-images.githubusercontent.com/19176319/69658551-42e57f80-1031-11ea-8c22-a9716c7d709d.png)

SVGs https://github.com/ErinBecker/carpentries_art/blob/master/skin_tones.svg 
https://github.com/ErinBecker/carpentries_art/blob/master/rainbow.svg

**Comment by kerchner** [comment]
@ErinBecker We should save the Warhol design for when the conference is held in Pittsburgh!

**Comment by BinxiePeterson** [comment]
I had a go at two designs. Can be used for front and back of the T-shirt respectively, or just one of the two. Or a combination of the two. Fun fact: I drew everything (except the barren tree) with shapes!
![Design1](https://user-images.githubusercontent.com/17334907/70622445-9d333280-1c24-11ea-8eea-2c56a0ecbaeb.PNG)
![Design2](https://user-images.githubusercontent.com/17334907/70622446-9d333280-1c24-11ea-9474-26ca236f8a71.PNG)

**Comment by lauracion** [comment]
I love Erin's "you belong in the Carpentries" designs and Binxie's Carpen:deciduous_tree:Con2020 design equally

**Comment by ousodaniel** [comment]
![CarpConLogo](https://user-images.githubusercontent.com/27581894/72845955-b06c0000-3cb0-11ea-9c89-2bca7c3c0e1b.png)

**Comment by chennesy** [comment]
![Asset 2](https://user-images.githubusercontent.com/1714236/74378861-512f7600-4dac-11ea-8703-6274d133b37f.png)

**Comment by ragamouf** [comment]
![Screen Shot 2020-02-17 at 11 47 29 am](https://user-images.githubusercontent.com/46695862/74616363-6aa13b00-517b-11ea-8486-4d34a84ec81a.png)

**Comment by Denubis** [comment]
https://www.overleaf.com/read/jczdwtbvkpsm is the overleaf page in case you want to copy/fiddle with the base code.

**Comment by anenadic** [comment]
> ![Screen Shot 2020-02-17 at 11 47 29 am](https://user-images.githubusercontent.com/46695862/74616363-6aa13b00-517b-11ea-8486-4d34a84ec81a.png)
> 
> This is a little nicer
> ![Screen Shot 2020-02-17 at 3 11 32 pm](https://user-images.githubusercontent.com/46695862/74623216-d5f90600-5197-11ea-9f51-141bb86e4c4f.png)
> 
> Actually this one is the best, via zoom tutorial with @Denubis in overleaf
> <img alt="Screen Shot 2020-02-18 at 4 22 46 pm" width="585" src="https://user-images.githubusercontent.com/46695862/74706405-0362b400-526b-11ea-927a-b1a31758edda.png">

Wow, I like the text on t-shirt very much - I do not think we had it so far, we always concentrate on designing a logo.

**Comment by chrispunjoku** [comment]
I agree, Aleksandra. The text being *.**orange**.* or *.**white**.* on a
black shirt will be alluring.



Chris Prince Udochukwu *Njọkụ*, Ph.D.
Computer Communications Centre
University of Nigeria, Nsukka 410001
@DrCPUNjoku

 We mustn't remain with old ways of doing things,

especially if they're not yielding optimum results.

**Comment by cwant** [comment]
Maybe I'm not ready to let go of Valentines Day:

![carpentry-con1](https://user-images.githubusercontent.com/672104/75271662-caba6180-57b9-11ea-8de5-500faedad87a.png)

**Comment by mariabnd** [comment]
![carpentries-logo](https://user-images.githubusercontent.com/33788128/75366909-c1b3b800-58bf-11ea-9aa5-97eaabe6db7b.png)

**Comment by trallard** [comment]
It took me forever but here are some designs. Some could be used for flyers/posters as they are quite colour heavy and I also created a background less one:

![Asset 1@500x](https://user-images.githubusercontent.com/23552331/75447578-91bcf100-5961-11ea-8031-89ae27985d12.png)
 
![Asset 2@500x](https://user-images.githubusercontent.com/23552331/75447595-9a152c00-5961-11ea-925d-30a62ca90395.png)
![Asset 3@500x](https://user-images.githubusercontent.com/23552331/75447599-9b465900-5961-11ea-978c-69bd7171e4d7.png)
![Asset 4@500x](https://user-images.githubusercontent.com/23552331/75447604-9c778600-5961-11ea-9eb8-4df19261f3d1.png)
![Asset 5@500x](https://user-images.githubusercontent.com/23552331/75447616-a00b0d00-5961-11ea-96ba-5224cb27c1d6.png)

**Comment by anenadic** [comment]
Ah, super nice @trallard!

**Comment by elssam** [comment]
#### First.

![image](https://user-images.githubusercontent.com/13832075/75928932-bdfbd480-5e6f-11ea-8470-f7c96bb9b6b0.png)

#### Second.

![image](https://user-images.githubusercontent.com/13832075/75928996-e97ebf00-5e6f-11ea-9369-68401f5e2e0e.png)

**Comment by ErinBecker** [comment]
These are both so pretty @elssam! I love them!

**Comment by lauracion** [comment]
:heart_eyes: @elssam! both are awesome - I have a slight preference for the second one. For me, it ties with @BinxiePeterson's carpen:deciduous_tree:Con and :rainbow: "You belong to The Carpentries" by @ErinBecker. Aaaah, I'd have to role a dice to decide!

**Comment by sstevens2** [comment]
Thank you all for your t-shirt submissions!  They are all so wonderful I'm a little grateful we won’t have to decide among them.  Due to the cancellation of CarpentryCon2020 in person, we will not be creating a t-shirt this year.  Hope to have you involved in a future CarpentryCon t-shirt design.

**Comment by ErinBecker** [comment]
I wanted to second @sstevens2 appreciation of all of the designs submitted here! Even though we won't be creating a tshirt for this year's CarpentryCon event, the artwork submitted here has been incredibly useful for our new annual report design (to be released soon). A HUGE thank you to @trallard and @BinxiePeterson for allowing your artwork to be featured in the 2019 annual report!
