### ISSUE TITLE
Quick Tips for Teaching and Learning Online by The Carpentries Community

### ISSUE THREAD

**Issue by serahrono** [carpentries/conversations#24]
### Context
Due to stringent measures taken to help curb the spread of COVID-19, remote teaching and learning is quickly becoming a priority for institutions around the world. The Carpentries community has extensive experience teaching and learning online, and we hope to combine responses to the prompts below in a blog post to share tips with others that may be starting out in this regard. 

### How to Contribute

Please add your responses under each prompt [in this Google Doc](https://docs.google.com/document/d/1MdmrNn5g2oa2AA6EGYZhyDx-O_YOoH_HqNGsmP6LKIo/edit?usp=sharing), taking care not to delete other people’s contributions. Your responses can be as long and as detailed as you like, and examples and anecdotes are welcome as well. 

You are also welcome to share your responses under this issue.

### Timeline

Contributions to this document are welcome  between Friday, 13 March 2020 and Tuesday, 17 March 2020. 

Serah Rono will edit all contributed responses into a narrative for a blog post that will be published on The Carpentries blog on Wednesday, 18 March. Everyone who contributes will be listed as a co-author.

#### Tips for Teaching Online
- In summary, what are the most notable differences between teaching online and in-person?
- What are the most important things to keep in mind as one prepares to teach an online class?
- How does one foster a safe and inclusive environment for learning online?
- What tools would you recommend using in teaching an online class, and what purpose do they serve?
- How does one capture the attention of learners and encourage participation in an online class?
- What are other tips to keep in mind, not covered above, for teaching online?
- What are things to avoid doing while teaching an online class?
- What does post-lesson follow up look like when teaching online?
- What resources (guides, books, videos, articles, etc) for online teaching would recommend to others? 

#### Tips for Learning Online
- How can a learner prepare for an online class?
- What tips should a learner employ when attending an online class?
- How best can a learner engage with others in an online class?
-  What resources (guides, books, videos, articles, etc) for online learning would recommend to others?

**Comment by serahrono** [comment]
Collaborative blog posts by Carpentries community in March 2020 as a result of this call for contributions
+ March 19, [Tips for Teaching Online from The Carpentries Community](https://carpentries.org/blog/2020/03/tips-for-teaching-online/)
+ March 30, [More Community-Contributed Tips for Teaching Online](https://carpentries.org/blog/2020/03/more-tips-teaching-online/)

Other relevant resources:
+ Official guidelines and recommendations for teaching pilot-phase Carpentries workshops [can be found here on The Carpentries website](https://carpentries.org/online-workshop-recommendations/).
+ A more complete curated list of resources relevant for online workshops is available [here](https://docs.carpentries.org/topic_folders/hosts_instructors/resources_for_online_workshops.html)

**Comment by kariljordan** [comment]
Closing this issue as all of the feedback has been incorporated and the teaching tips are on our website.
