### ISSUE TITLE
CarpentryCon 2020 - 24 hours travelling conference for its community

### ISSUE THREAD

**Issue by malvikasharan** [carpentries/conversations#25]
## Summary

An idea for 24 hours travelling conference for CarpentryCon 2020

## Context

CarpentryCon this year has announced that it will not even take place virtually. I appreciate the amount of work the organization committee has put in, and I am proud of their decision.

However, this conference is community-led, and if any community is well-equipped to do a global conference, it is Carpentries.

## Idea

The Carpentries community members are in literally all time zones. If we can reach out to local leaders who would like to host an online conference for 1-2 hours each in their time zones, we can coordinate to have a complete 24 hours conference.

## How can we run it?

- The Carpentries bug bbq
- Twitter conference
- Online discussion sessions on Zoom
- Livestreaming talks
- more ideas?

## What we need?

- Community input on if this is a viable idea.
- If yes, what would they like to hear or talk about or build?
- Zoom accounts where community members can log in or youtube live streaming.
- People who are willing to commit 1-2 hours of their time convenient in their time zones.
- Local community leaders who want to showcase their community work and share success and failure stories with others.

## Resources:

- All the lessons learned in the community!
- Checklist for remote events: https://deploy-preview-962--the-turing-way.netlify.com/remote_collaboration/checklist/checklist.html
- Facilitating remote events: https://deploy-preview-1008--the-turing-way.netlify.com/introduction/introduction

**Comment by mkuzak** [comment]
- here is one more resource (thanks to @ tobyhodges) https://medium.com/@kording/how-to-run-big-neuro-science-conferences-online-neuromatch-io-49c694c7e65d
- also it would nice to have some up-skilling sessions

**Comment by malvikasharan** [comment]
+10000 for Skill up.

**Comment by dpshelio** [comment]
I'm happy to run a workshop (or multiple at different times if needed) about translations! Or multiple aimed at different audiences (technical/no-technical - for infrastructure maintainers and for translators).

**Comment by kerchner** [comment]
Our planning group for CarpentryConnect DC supports this idea and we are willing to run a Birds-of-a-Feather session that we will structure around interests in the greater Washington, DC region.

**Comment by mkuzak** [comment]
the good thing is that we can have unlimited number of parallel sessions :)

**Comment by malvikasharan** [comment]
I have contacted the CarpentryCon committee (Dan is one of them), let's see what they think :)
Have a nice weekend everyone. Let's pick this up next week.

**Comment by anenadic** [comment]
I very much like the idea of producing something (such as bbq) in addition to "Local community leaders who want to showcase their community work and share success and failure stories with others."

**Comment by malvikasharan** [comment]
@anenadic @serahrono Can we invite the regional coordinator to this discussion?

**Comment by serahrono** [comment]
go for it @malvikasharan! [This page on the website](https://carpentries.org/regionalcoordinators/) has contact details for all Carpentries' regional coordinators

**Comment by anenadic** [comment]
@malvikasharan I can pass the message to people around the UK who are (local) workshop coordinators

**Comment by malvikasharan** [comment]
Update: People who commented here joined in to plan the CarpentryCon @ home, which was not a 24-hour conference but even more inclusive 7 weeks conference. Read details here: https://carpentries.org/blog/2020/12/thank-you-notes-by-core-team/.
