### ISSUE TITLE
Reference DC and SWC blog posts from #1?

### ISSUE THREAD

**Issue by wking** [carpentries/conversations#4]
The initial post for this repo went out in a few places:

* [discuss@][1]
* The [Data Carpentry blog][2]
* The [Software Carpentry blog][3]

Each of those directed feedback to #1 or blog post comments (with each blog post using “this post” and the discuss@ message pointing at the Data Carpentry post).  It's not clear to me if or how we plan on collecting that feedback/discussion in a single location (“interesting Disqus comments might get copied into #1”?).  Until we have a plan for that, it's probably worth linking from #1 to the two blog posts so interested readers can go check out any Disqus comments directly.

[1]: http://lists.software-carpentry.org/pipermail/discuss/2016-December/004931.html
[2]: http://www.datacarpentry.org/blog/conversations/
[3]: https://software-carpentry.org/blog/2016/12/conversations.html

**Comment by tracykteal** [comment]
Thanks I added a link to the blog posts on the initial post. We'll be bringing comments across, but we want to give people a chance to comment through different mediums, so the mode of communication isn't a barrier to participation.

**Comment by wking** [comment]
> Thanks I added a link to the blog posts on the initial post.

That should be enough for discover.  Collecting comments in one place would be nice, but isn't critical.
