### ISSUE TITLE
Reigniting Community: Coffee with The Carpentries Executive Director (8 January 2024) - *Discussing staff layoffs and plans for moving forward*

### ISSUE THREAD

**Issue by OscarSiba** [carpentries/conversations#58]
_**Reigniting Community: Coffee with The Carpentries Executive Director, @kariljordan**_ is a series of six monthly open discussions to be hosted by Kari from January until June 2024 under the theme of 'Reigniting Community'. 

![Social Media Images (14)](https://github.com/carpentries/conversations/assets/132367843/da10f7f7-1037-446f-ab4f-bb530c6abf19)

_**8 January Session Focus**_: The focus of this discussion session and GitHub conversation issue, the first in the series, is to engage with The Carpentries community on the [recent staff layoffs](https://carpentries.org/blog/2023/12/saying-farewell-to-seven-carpentries-core-team-members/), and share some ideas on how we plan to collectively move forward in the near future. 

Kari will provide a summary of the discussions from this session in this conversation issue, including her answers to some of the questions that were raised at the session. If you missed the session and would like to pose a question or you attended it but have additional questions, please add them as comments below. 

This conversation issue will remain open and Kari will actively engage with your questions and comments until we open the conversation issue for next month's Reigniting Community session, which will focus on a different topic to be announced closer to the time.

**Comment by kariljordan** [comment]
**Summary of Coffee with The Carpentries Executive Director on 8 January 2024**

The first coffee with @kariljordan included ten attendees from the community and Core Team. We began with a welcome, introductions, and an overview of the Code of Conduct.

@kariljordan shared a short [presentation](https://docs.google.com/presentation/d/1lTlD2f_Sx9D7dvcGfq7T30x0oNhls7XJE1F9XW57RxE/edit#slide=id.g2acff3a7536_0_80) offering an overview of The Carpentries' 2023 fundraising projections and summary of the outcomes of our programmatic revenue projections. **_To make our 2024 budget realistic, we needed to reduce our income projections for both fundraising and programming._** That meant reducing our expenses by $500,000 in 2024, which led to reducing the size of our team from 16 persons to 9 persons. This fiscal year’s budget puts us in a secure position with >6 months of operating expenses in the bank.

In mid to late January, two blog posts will be shared with the community, providing an overview of 2024's programming, which Core Team members will support those initiatives, and how the community can support them.

Below are the questions and answers from the community session.

- Will this affect the transition to non-profit status from fiscally sponsored project?
-- We have received our 501(c)3 status. Our governance still wants us to spin out of a fiscally sponsored project status once we are in a better financial position to do so. Our FY24 budget puts us in a much better position with >6 months of operating expenses.

- Would you consider using artificial intelligence to be(come) a core data science skill? It feels like something that is not contrary to the core goals. Its inclusion would allow it to align with the funder’s priorities again.
-- Fundamental data skills are needed to thrive in AI. We can support this without moving away from our mission. For example, conversations about ethical AI as it relates to the Carpentries values. We have a place, but we need to figure out where funders would support what we're already doing
--Current lesson in beta: https://carpentries-incubator.github.io/machine-learning-librarians-archivists/

- How can we contribute to helping maintain the Workbench now that the lead developer is no longer with the Carpentries? Who is leading this?
--Erin Becker and Rob Davey are the primary individuals who will support the Workbench moving forward. If you would like to get involved, please email team at carpentries dot org.

Thank you to everyone who attended the session. The community is welcome to add more questions and comments to this issue.

**Comment by kariljordan** [comment]
Thank you for engaging with us during the month's conversation. This issue is now closed, and we are discussing the next in https://github.com/carpentries/conversations/issues/59.
