### ISSUE TITLE
Reigniting Community: Coffee with The Carpentries Executive Director (27 June): Toolkit of IDEAS

### ISSUE THREAD

**Issue by kariljordan** [carpentries/conversations#64]
_**Reigniting Community: Coffee with The Carpentries Executive Director, [@kariljordan](https://github.com/kariljordan)**_ is a series of monthly open discussions hosted by Kari from January until June 2024 under the theme of 'Reigniting Community'.

The next session is scheduled for 27 June at 18:00 UTC. 
 
![Social Media Images (20)](https://github.com/carpentries/conversations/assets/132367843/dbb89777-6594-4450-a4e2-0d3da6431240)

_**27 June Session Focus**_: The focus of this community session and accompanying GitHub conversation issue, the final one in the series, is to engage with the community on the [Toolkit of IDEAS resource](https://zenodo.org/records/10391883).

_**Previous sessions**_
The January session focused on the staff layoffs in December, and the summary of the discussions from that session can be found in [the session’s GitHub conversation issue.](https://github.com/carpentries/conversations/issues/58). 

The February session focused on continuing work at The Carpentries following the staff layoffs, as well as the Core Team members supporting that work. The summary of the discussions from that session can be found in [the session’s GitHub conversation issue.](https://github.com/carpentries/conversations/issues/59).

The March session focused on the community survey responses summarised in our recently released 2023 Carpentries Community Survey Evaluation Report. The summary of the discussions from that session can be found in [the session’s GitHub conversation issue.](https://github.com/carpentries/conversations/issues/61).

The April session engaged with the community on the outcomes of Year 4 of The Carpentries’ strategic plan. The summary of the discussions from that session can be found in [the session’s GitHub conversation issue](https://github.com/carpentries/conversations/issues/62).

The May session was canceled. 

_**This GitHub conversation issue**_: Kari will provide a summary of the discussions from this session in this conversation issue, including her answers to some of the questions that were raised at the session. If you missed the session and would like to pose a question or you attended it but have additional questions, please add them as comments below.

This conversation issue will remain open for a month and Kari will actively engage with your questions and comments during that period. This session is the last one in _Reigniting Community_ session.Thank you to everyone who participated and engaged with Kari over these past six months.

**Comment by jas58** [comment]
Do I run this list (IDEAS toolkit) as an invited instructor of a centrally organized workshop?  Or does someone in Core make that push?  I understand it is my responsibility if I organize my own local workshop.

**Comment by kariljordan** [comment]
Summary of Coffee with The Carpentries Executive Director on 27 June 2024:

The fifth and last coffee with @kariljordan began with a welcome and logistics segment followed by introductions, where participants share their names, affiliations, and reasons for joining the call. We also shared the last thing we drank!

@kariljordan shared a short [presentation](https://docs.google.com/presentation/d/12pj5nXFQf30GpyyG_CZRAqtrgP2AT6zpAnzfzH09Y0s/edit#slide=id.g22e5450dc20_0_148) offering an overview of our Toolkit of IDEAS, supported by this GitHub issue and the Zenodo link. 

In the breakout groups, participants discussed various barriers that prevent learners from completing Carpentries workshops and ways to ensure data enthusiasts feel included:
- Room 1 addressed the challenge of varying experience levels among instructors and learners, along with time constraints. 
- Room 2 discussed the issue of lessons being perceived as too advanced despite being introductory and accessibility issues faced by parents with responsibilities. 
- Room 3 focused on misleading workshop titles, the importance of setting clear expectations regarding pace and content, and the need for consistent scheduling.

Each group also explored specific solutions to these challenges:
- Room 1 emphasized the importance of logistics and inclusivity for participants from diverse backgrounds. 
- Room 2 suggested institutional support for tools aiding auditory accessibility. 
- Room 3 highlighted the value of post-workshop support time and setting clear expectations for both learners and instructors. Additionally, this room proposed facilitating meetings for instructors to enhance team collaboration. >>> We do this now! cc @danielle06 @sheraaronhurt 

The breakout group discussions were followed by reports in the main room, where each group shared their findings and suggestions. The agenda concluded with a Q&A session, providing an opportunity for participants to address any remaining questions and share additional insights.

The community is encouraged to share your feedback directly on this issue.

**Comment by kariljordan** [comment]
> Do I run this list (IDEAS toolkit) as an invited instructor of a centrally organized workshop? Or does someone in Core make that push? I understand it is my responsibility if I organize my own local workshop.

Great question! Let's hear from @danielle06 and @elletjies as they lead coordinating centrally organized workshops.

**Comment by elletjies** [comment]
@jas58 we encourage all instructors to make workshops as accessible as possible (centrally and self-organised). Thank you for the nudge Jennifer, @danielle06 I think we should add a link to the Toolkit of IDEAS into our introduction emails?

**Comment by danielle06** [comment]
Thanks for responding, @elletjies ! I agree, we should add it to the introduction email. It's important for both Instructors and hosts to utilise the ideas in the toolkit. I will make sure it is included in our updated emails for automation.

**Comment by kariljordan** [comment]
Thank you everyone for your feedback on this issue!
