### ISSUE TITLE
Cross-posting blog post

### ISSUE THREAD

**Issue by rgaiacs** [carpentries/conversations#8]
I believe that some blog posts should be post on Software Carpentry and Data Carpentry website. Or we should have a blog post for the Carpentry where those blogs should be post. For example, http://www.datacarpentry.org/blog/sa-partner/ is about a join partnership write by our new partner and because of it I believe should be available on both websites. If Software Carpentry and/or Data Carpentry executive director prefer to write their own blog post I'm very happy with that option as long as the blog posts announcements link to each other and the publication is coordinated to be on the same day.

**Comment by tracykteal** [comment]
Hi @rgaiacs. Anelda put in a PR to both websites. Her PR is here. 

https://github.com/swcarpentry/website/pull/643

Can you merge?

**Comment by rgaiacs** [comment]
Thanks for point it to me. I first found the post on Twitter.

> Can you merge?

My user don't have more write permission to swcarpentry/website. @jduckles need to merge it AFAIK.

**Comment by ErinBecker** [comment]
Thanks for the feedback @rgaiacs. That post was coordinated to go up on the same day, but the Software Carpentry blog takes longer to build (it's much bigger!). In general, we do try to coordinate cross-posted blog posts. I agree that we should also link between the two. Ok to close this issue?
